#!/usr/bin/env python3
"""Run the full official-resolver differential gate.

The expected rows are generated by the installed zigbee-herdsman-converters
package. The bundled C++ matcher sources under tests/runtime are compiled and
must reproduce the official selection for every fingerprint and zigbeeModel
probe. This is intentionally a hard gate: a new upstream definition that the
runtime cannot select must stop publication.
"""
from __future__ import annotations

import json
import os
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TESTS = ROOT / "tests"
RUNTIME = TESTS / "runtime"


def run(command: list[str], *, env: dict[str, str] | None = None) -> subprocess.CompletedProcess[str]:
    print("+", " ".join(command), flush=True)
    return subprocess.run(command, cwd=ROOT, env=env, check=True, text=True)


def main() -> int:
    bundle = os.environ.get("Z2M_BUNDLE", str(ROOT / "dist" / "z2m_bundle.candidate.bin"))
    expect_json = os.environ.get("Z2M_EXPECT_JSON", "/tmp/z2m_expect.json")
    expect_tsv = os.environ.get("Z2M_EXPECT_TSV", "/tmp/z2m_expect.tsv")
    executable = os.environ.get("Z2M_MATCHER_DIFF", "/tmp/z2m_matcher_diff")

    env = os.environ.copy()
    env["Z2M_EXPECT_JSON"] = expect_json
    env["Z2M_EXPECT_TSV"] = expect_tsv
    run(["node", str(ROOT / "tools" / "export_expect.mjs")], env=env)

    expected_rows = json.loads(Path(expect_json).read_text(encoding="utf-8"))
    expected_count = len(expected_rows)
    minimum = int(os.environ.get("Z2M_MIN_PROBES", "7290"))
    if expected_count < minimum:
        raise SystemExit(
            f"official probe set unexpectedly shrank: {expected_count} < {minimum}"
        )

    run([
        "g++", "-std=c++17", "-O2", "-I", str(RUNTIME / "include"),
        "-o", executable,
        str(TESTS / "matcher_diff.cpp"),
        str(RUNTIME / "converter_matcher.cpp"),
        str(RUNTIME / "converter_bundle.cpp"),
        str(RUNTIME / "converter_endpoint.cpp"),
    ])
    result = subprocess.run(
        [executable, bundle, expect_tsv],
        cwd=ROOT,
        text=True,
        capture_output=True,
    )
    output = (result.stdout or "") + (result.stderr or "")
    print(output, end="" if output.endswith("\n") else "\n")
    if result.returncode != 0:
        raise SystemExit(result.returncode)
    summary = re.search(r"\btotal=(\d+) agree=(\d+) disagree=(\d+)\b", output)
    if not summary:
        raise SystemExit("matcher differential gate did not print a summary")
    total, agree, disagree = (int(value) for value in summary.groups())
    if total != expected_count:
        raise SystemExit(
            f"matcher probe count mismatch: matcher={total} official={expected_count}"
        )
    if agree != total or disagree != 0:
        raise SystemExit(
            "matcher differential gate failed: "
            f"total={total} agree={agree} disagree={disagree}"
        )
    print(
        "PASS: official resolver differential gate " 
        f"(official_probes={expected_count} agree={agree} disagree={disagree})"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
